AtlasOfLivingAustralia/collectory-plugin

- grails-app/controllers/au/org/ala/collectory/DataController.groovy
- grails-app/controllers/au/org/ala/collectory/TempDataResourceController.groovy
- grails-app/services/au/org/ala/collectory/CollectoryAuthService.groovy
Add CollectoryAuthService to fix the checkApiKey issue.
> Fix the checkApiKey issue

- grails-app/controllers/au/org/ala/collectory/DataController.groovy
Add CollectoryAuthService.groovy in collectory-plugin
> Add CollectoryAuthService in collectory-plugin

- grails-app/conf/CollectoryUrlMappings.groovy
Fixed some authentication issues and merged new code from collectory to collectory-plugin
> Fixed some authentication issues and merged new code

- grails-app/controllers/au/org/ala/collectory/MessagesController.groovy
> Fixed MessageController

- grails-app/controllers/au/org/ala/collectory/ManageController.groovy
- grails-app/views/manage/list.gsp
Fixed some authentication issues about CollectoryAuthService
> Fixed some authentication issues about CollectoryAuthService

- grails-app/services/au/org/ala/collectory/IptService.groovy
GUID for created data resource is resource URL
> Create GUID for data resource

- CollectoryGrailsPlugin.groovy
- grails-app/conf/spring/resources.groovy
- grails-app/controllers/au/org/ala/collectory/MessagesController.groovy
- grails-app/i18n/messages_zh.properties
- grails-app/views/layouts/_global.gsp
- grails-app/views/layouts/generic.gsp
Fix the bug of i18n javascript.
> Fix the bug of i18n javascript

- grails-app/controllers/au/org/ala/collectory/IptController.groovy
- grails-app/services/au/org/ala/collectory/IptService.groovy
API Key is supplied via a cookie to ensure key is not part of the URL and since the scan is a plain get without a payload. See IptController for documentation.
API Key requires the following configuration settings in ala-collectory-config.properties which are not part of the standard defaults:
security.apikey.checkEnabled=true
security.apikey.serviceUrl=http://auth.ala.org.au/apikey/ws/check?apikey=
> Allow IPT scan to use API key for authentication.

- web-app/js/collectory.js
Open an email dialog on Chrome.
> Fix the issue of open an email dialog on Chrome

- grails-app/views/public/show.gsp
> Missing collection stats

- grails-app/controllers/au/org/ala/collectory/ProviderGroupController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/au/org/ala/collectory/GbifService.groovy
- grails-app/views/dataResource/gbifUpload.gsp
this changes the gbif file upload tool to a download tool which takes a
URL to a GBIF download archive
> gbif file download fix

- grails-app/controllers/au/org/ala/collectory/ProviderGroupController.groovy
> Merge last fix into hotfix for deployment

- grails-app/services/au/org/ala/collectory/CrudService.groovy
- grails-app/views/providerMap/_form.gsp
Fixes the provider map Unknown Error happening when you are adding a new provider map.
> Unknown Error in adding a new provider map

- .travis.yml
- grails-app/conf/CollectoryUrlMappings.groovy
- grails-app/controllers/au/org/ala/collectory/TempDataResourceController.groovy
- grails-app/domain/au/org/ala/collectory/DataResource.groovy
- grails-app/domain/au/org/ala/collectory/TempDataResource.groovy
- grails-app/services/au/org/ala/collectory/CrudService.groovy
- grails-app/taglib/au/org/ala/collectory/CollectoryTagLib.groovy
- grails-app/views/dataResource/rights.gsp
- grails-app/views/public/showDataResource.gsp
This PR is related to this [issue](AtlasOfLivingAustralia/sandbox#28). It contains modifications to temp data resource domain. And added some additional licenses to Data resource domain.
> Uploads sandbox changes

- grails-app/controllers/au/org/ala/collectory/DataProviderController.groovy
- grails-app/domain/au/org/ala/collectory/DataResource.groovy
- grails-app/services/au/org/ala/collectory/GbifRegistryService.groovy
- grails-app/views/dataProvider/list.gsp
Adds ability to store the GBIF issued DOI on the data_resource table and adds a utility asynchronous link to update all GBIF registrations
> Enable use of GBIF DOIs, and utility to update all registrations

- grails-app/services/au/org/ala/collectory/GbifRegistryService.groovy
Simple typo.
Big consequences.
> Corrects Type that breaks registrations and updates

- grails-app/conf/CollectoryUrlMappings.groovy
Fix for https://github.com/AtlasOfLivingAustralia/collectory-plugin/issues/117
> Allow /ws/contacts without id

- grails-app/views/manage/list.gsp
Fix glyphicon icones
Change the way to show and hide class (jquery)
> Fix few issues on manage/list.gsp

- crowdin.yml
Following the conversation in https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/40 I created this crowdin-cli configuration to keep in sync this ALA repo (and others in short) with crowdin easily.
More info in the configuration comments.
> Added crowdin configuration to sync ALA with crowdin via crowdin-cli

- grails-app/controllers/au/org/ala/collectory/DataProviderController.groovy
- grails-app/controllers/au/org/ala/collectory/ManageController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/au/org/ala/collectory/GbifRegistryService.groovy
- grails-app/services/au/org/ala/collectory/GbifService.groovy
- grails-app/views/dataProvider/gbif/list.gsp
- grails-app/views/dataProvider/list.gsp
- src/groovy/au/org/ala/collectory/resources/gbif/GbifDataSourceAdapter.groovy
Add new functionality to create Data Provider from the GBIF organizations ("Import from GBIF" in "View all data providers")
New configuration param (countryCode) in grailsApplication.config to default the selected country in the new screen.
Move getCountryMap() to GbifService.groovy to avoid duplication
> Import data provider from gbif

- grails-app/services/au/org/ala/collectory/CrudService.groovy
**Create collection:**
Add **institution** field to set the institution for the collection.
POST /collectory/ws/collection
```
{
"name": "my collection",
"institution": {
"uid": "in0"
},
"recordsMapping": {
"institutionCodes": "IN_CODE_0",
"collectionCodes": "CO_CODE_0"
}
}
```
**Create dataResource:**
Add **uid** field to set the uid for the dataResource.
Add **dataLinks** array field to create DataLinks between dataResource, collection and institution
POST /collectory/ws/dataResource
```
{
"uid": "dr123",
"name": "my dataresource,
"institution": {
"uid": "in0"
},
"dataProvider": {
"uid": "dp0"
},
"dataLinks": ["in0", "co0"],
"connectionParameters": {
"url": "file:////data/dr.zip",
"automation": False,
"termsForUniqueKey": ["occurrenceID"],
"strip": False,
"incremental": False, …
```
> Add fields in Collectory WS for collection/dataResource creation

- grails-app/services/au/org/ala/collectory/IptService.groovy
> Fail on validation errors saving resources

- grails-app/domain/au/org/ala/collectory/Collection.groovy
Fix for #181. Tested in collectory demo.
> Increase maxSize in subcollections.

- grails-app/domain/au/org/ala/collectory/DataResource.groovy
Related to https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/397
> GenomicDNA and EnvironmentalDNA content types
